```{r prepare}

options(download.file.method = "libcurl", repos=c("CRAN" = "https://cran.r-project.org/"))

ipak <- function(pkg){
    new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
    if (length(new.pkg)) 
        install.packages(new.pkg, dependencies = TRUE)
    sapply(pkg, require, character.only = TRUE)
}

# usage
packages <- c("rmarkdown")
ipak(packages)



```



```{r run}

# LOAD DATA
et_raw_dcns <- read.table("data/ET_DATABASE_DCNS.txt", header = TRUE, sep=" ")
et_raw_dcns <- et_raw_dcns[which(et_raw_dcns$subj != "1100981"),]
et_raw_dcns <- et_raw_dcns[which(et_raw_dcns$subj != "0"),]

et_raw_h2oil <- read.table("data/ET_DATABASE_NEUROH2OIL.txt", header = TRUE, sep=" ")
et_raw_h2oil <- et_raw_h2oil[which(et_raw_h2oil$subj != "8038"),]
et_raw_h2oil <- et_raw_h2oil[which(et_raw_h2oil$subj != "0"),]
et_raw_h2oil <- et_raw_h2oil[which(et_raw_h2oil$subj != "999999"),]

et_raw <- rbind(et_raw_dcns, et_raw_h2oil)

#et_raw <- read.table("data/ET_DATABASE.txt", header = TRUE, sep=" ")
colnames(et_raw)[colnames(et_raw)=="test.x"] <- "test"


# PRESELECT
#et_raw <- et_raw[which(et_raw$subj >110000), ]
#et_raw <- et_raw[which(et_raw$subj <999999), ]
et_raw <- unique(et_raw)

# PREPROCESS
rmarkdown::render("scripts/preprocess.Rmd",
                        output_file = "../results/preprocess.html")

# IMPUTE
rmarkdown::render("scripts/impute.Rmd",
                        output_file = "../results/impute.html")

# PCA
rmarkdown::render("scripts/pca.Rmd",
                        output_file = "../results/pca.html")

# APPLY PCA
rmarkdown::render("scripts/apply_pca.Rmd",
                        output_file = "../results/applypca.html")

```
